import type { NextPage } from 'next'
import Head from 'next/head'
import useDark from '../hooks/useDark'

const Home: NextPage = () => {
  const { isDark, toggleDark } = useDark()
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="font-mono text-3xl">HelloWorld</div>
      <div
        className="icon-btn !outline-none"
        onClick={() => toggleDark()}
      >
        <div className={isDark ? 'i-carbon-moon' : 'i-carbon-sun'} />
      </div>
      <div className="icon-btn i-carbon-logo-github"></div>
    </div>
  )
}

export default Home
