import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic'
import TypeIt from 'typeit-react'

const NavBar = dynamic(() => import('../components/NavBar'), { ssr: false })

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dewey Ou</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className="font-mono text-xl">
        {/* ti-cursor */}
        <TypeIt
          options={{
            strings: [
              'Hello',
              'I am Dewey Ou',
              'A Frontend Engineer',
              'Working at ByteDance',
            ],
            speed: 50,
            waitUntilVisible: true,
          }} />
      </div>
    </div>
  )
}

export default Home
