import type { NextPage } from 'next'
import Head from 'next/head'
import Summary from '../components/Summary'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dewey Ou</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Summary />
    </div>
  )
}

export default Home
